### PR TITLE
ALLYPD-3515 Website Updates

### PR DESCRIPTION
**Pull request by SamPeck**
Initial updates to website

### CODE REVIEW

**Comment by SamPeck** [comment]
Let me know if there's an issue with merging this anyway by the end of this week.

**Review by Gommorach — CHANGES_REQUESTED** [review]
I found one issue that probably needs to be addressed:
On the Request Demo page, the Courses and Websites navigation elements are broken. 
They link to an anchor point, so they resolve to `demo.html#ally-for-web` instead of `index.html#ally-for-web`. The click event also gets 'intercepted' by the smooth scroll handling function on line 255 in `ally.js`, which throws an error because it can't find the matching HTML elements.

**Comment by SamPeck** [comment]
Changes made based on review

**Review by Gommorach — APPROVED** [review]

**Comment by Gommorach** [comment]
LGTM, feel free to merge

**Pull request merged**
