### PR TITLE
Initial design and dev

### PR DESCRIPTION
**Pull request by SamPeck**
Design and dev for website update including Ally for web and other amendments.

### CODE REVIEW

**Comment by SamPeck** [comment]
Still waiting on Elisa to give me Eloqua codes and for Blackboard marketing to upload and make changes to the YouTube videos I still need to embed.

**Comment by simong** [comment]
Looks good to me. I've pushed a commit so that the target element (e.g. #ally-for-web) gets scrolled into view just below the navigation rather than the top of the screen.

**Comment by simong** [comment]
I'll hold off merging until we have those codes from Elisa.

**Comment by SamPeck** [comment]
Cool, thank you Simon, taking the in the scroll minus the height of the nav header makes sense. Another issue I'm having is controlling the scroll position when using `id` hashes.

**Comment by SamPeck** [comment]
Ready for review and form tests for the new 'interest' select menu (Back to @simong)

**Pull request merged**
